import { 
	removeFieldCheck,
	elapsedDays,
	hmacHash
} from '@/utils/function-anonymaze';


// Define a mapping of check names to function references and parameters
export const anonChecks = [
	{
		name: 'anon_1',
		desc: 'Remove the record_id',
		prec: null,
		precParams: null,
		func: removeFieldCheck,
		params: ["bl_record_id"],

	},
	{
		name: 'anon_2',
		desc: 'Elapsed Days from Date of first pathological diagnosis (bl_1st_pathol_ddiag) for all date',
		prec: null,
		precParams: null,
		func: elapsedDays,
		params: ["bl_1st_pathol_ddiag", ["bl_dconsent", "bl_dor", "bl_drug1_start", "bl_drug1_end",
				"bl_drug2_start", "bl_drug2_end", "bl_drug3_start", "bl_drug3_end", "bl_menopausal_dstart",
				"bl_123_surv_dstart", "bl_123_surv_dend", "bl_123_sys_ther_pre_dstart", "bl_123_sys_ther_pre_dend", 
				"bl_123_sys_ther_post_dstart", "bl_123_sys_ther_post_dend", "bl_123_sys_ther_pal_dstart",
				"bl_123_sys_ther_pal_dend", "bl_1_radio_set_dstart", "bl_1_radio_set_dend", "bl_23_radio_lung_dstart",
				"bl_23_radio_lung_dend", "bl_23_radio_liv_dstart", "bl_23_radio_liv_dend", "bl_23_radio_bone_dstart", 
				"bl_23_radio_bone_dend", "bl_23_radio_soft_dstart", "bl_23_radio_soft_dend", "bl_23_radio_lymph_dstart",
				"bl_23_radio_lymph_dend", "bl_23_radio_sero_dstart", "bl_23_radio_sero_dend", "bl_23_radio_oth_dstart", 
				"bl_23_radio_oth_dend", "bl_123_limb_dproc", "bl_1_abla_dproc", "bl_23_abla_dproc_lung", "bl_23_abla_dproc_liv",
				"bl_23_abla_dproc_bone", "bl_23_abla_dproc_soft", "bl_23_abla_dproc_lymph", "bl_23_abla_dproc_serosal", 
				"bl_23_abla_dproc_oth", "bl_1_surg_dsurg", "bl_23_surg_dsurg_lung", "bl_23_surg_dsurg_liv", "bl_23_surg_dsurg_bone",
				"bl_23_surg_dsurg_soft", "bl_23_surg_dsurg_lymph", "bl_23_surg_dsurg_sero", "bl_23_surg_dsurg_oth", 
				"ufu_date", "ufu_menopausal_date", "ufu_oral_contra_start", "ufu_oral_contra_stop", "ufu_oral_contra2_start",
				"ufu_oral_contra2_stop", "ufu_oral_contra3_start", "ufu_oral_contra3_stop", "ufu_hormo_replac_start", "ufu_hormo_replac_stop",
				"ufu_hormo_replac2_start", "ufu_hormo_replac2_stop", "ufu_hormo_replac3_start", "ufu_hormo_replac3_stop", "ufu_dod",
				"ulr_date", "ulr_menopausal_date", "ulr_oral_contra_start", "ulr_oral_contra_stop", "ulr_hormo_replac_start",
				"ulr_hormo_replac_stop", "ulr_sys_ther_new_pre_start", "ulr_sys_ther_new_pre_end", "ulr_sys_ther_new_post_start", "ulr_sys_ther_new_post_end",
				"ulr_sys_ther_new_pal_start", "ulr_sys_ther_new_pal_end", "ulr_radio_start", "ulr_radio_end", "ulr_limbperf_date",
				"ulr_abla_date", "ulr_surg_date", "ulr_pathol_date", "ulr_dod", "udm_date", "udm_menopausal_date",
				"udm_oral_contra_start", "udm_oral_contra_stop", "udm_hormo_replac_start", "udm_hormo_replac_stop", "udm_sys_ther_new_pre_start",
				"udm_sys_ther_new_pre_end", "udm_sys_ther_new_post_start", "udm_sys_ther_new_post_end", "udm_sys_ther_new_pal_start", "udm_sys_ther_new_pal_end",
				"udm_radio_start", "udm_radio_end", "udm_limbperf_date", "udm_abla_date", "udm_surg_date", "udm_pathol_date", "udm_dod",
				"lfu_date", "lfu_menopausal_date", "lfu_oral_contra_start", "lfu_oral_contra_stop", "lfu_oral_contra2_start",
				"lfu_oral_contra2_stop", "lfu_oral_contra3_start", "lfu_oral_contra3_stop", "lfu_hormo_replac_start", "lfu_hormo_replac_stop",
				"lfu_hormo_replac2_start", "lfu_hormo_replac2_stop", "lfu_hormo_replac3_start", "lfu_hormo_replac3_stop", "lfu_dod",
				"lpr_date", "lpr_menopausal_date", "lpr_oral_contra_start", "lpr_oral_contra_stop", "lpr_hormo_replac_start",
				"lpr_hormo_replac_stop", "lpr_sys_ther_new_pre_start", "lpr_sys_ther_new_pre_end", "lpr_sys_ther_new_post_start", "lpr_sys_ther_new_post_end",
				"lpr_sys_ther_new_pal_start", "lpr_sys_ther_new_pal_end", "lpr_radio_lung_start", "lpr_radio_lung_end", "lpr_radio_liver_start",
				"lpr_radio_liver_end", "lpr_radio_bone_start", "lpr_radio_bone_end", "lpr_radio_soft_start", "lpr_radio_soft_end",
				"lpr_radio_lymph_start", "lpr_radio_lymph_end", "lpr_radio_sero_start", "lpr_radio_sero_end", "lpr_radio_oth_start",
				"lpr_radio_oth_end", "lpr_limbperf_date", "lpr_abla_date_lung", "lpr_abla_date_liver", "lpr_abla_date_bone",
				"lpr_abla_date_soft", "lpr_abla_date_lymph", "lpr_abla_date_serosal", "lpr_abla_date_oth", "lpr_surg_date_lung",
				"lpr_surg_date_liver", "lpr_surg_date_bone", "lpr_surg_date_soft", "lpr_surg_date_lymph", "lpr_surg_date_serosal",
				"lpr_surg_date_oth", "lpr_pathol_date", "lpr_dod", "sfu_date", "sfu_menopausal_date", "sfu_oral_contra_start", "sfu_oral_contra_stop",
				"sfu_oral_contra2_start", "sfu_oral_contra2_stop", "sfu_oral_contra3_start", "sfu_oral_contra3_stop", "sfu_hormo_replac_start",
				"sfu_hormo_replac_stop", "sfu_hormo_replac2_start", "sfu_hormo_replac2_stop", "sfu_hormo_replac3_start", "sfu_hormo_replac3_stop", "sfu_dod",
				"spr_date", "spr_menopausal_date", "spr_oral_contra_start", "spr_oral_contra_stop", "spr_hormo_replac_start", "spr_hormo_replac_stop",
				"spr_sys_ther_new_pre_start", "spr_sys_ther_new_pre_end", "spr_sys_ther_new_post_start", "spr_sys_ther_new_post_end", "spr_sys_ther_new_pal_start",
				"spr_sys_ther_new_pal_end", "spr_radio_lung_start", "spr_radio_lung_end", "spr_radio_liver_start", "spr_radio_liver_end",
				"spr_radio_bone_start", "spr_radio_bone_end", "spr_radio_soft_start", "spr_radio_soft_end",
				"spr_radio_lymph_start", "spr_radio_lymph_end", "spr_radio_sero_start", "spr_radio_sero_end", "spr_radio_oth_start",
				"spr_radio_oth_end", "spr_limbperf_date", "spr_abla_date_lung", "spr_abla_date_liver", "spr_abla_date_bone",
				"spr_abla_date_soft", "spr_abla_date_lymph", "spr_abla_date_serosal", "spr_abla_date_oth", "spr_surg_date_lung",
				"spr_surg_date_liver", "spr_surg_date_bone", "spr_surg_date_soft", "spr_surg_date_lymph", "spr_surg_date_serosal",
				"spr_surg_date_oth", "spr_pathol_date", "spr_dod", "lsu_status_date", "lsu_dod", "lsu_clinical_trials_dstart",
				"lsu_clinical_trials_dend", "lsu_clinical_trials_dstart_2", "lsu_clinical_trials_dend_2", "lsu_clinical_trials_dstart_3", "lsu_clinical_trials_dend_3"]],

	},
		{
		name: 'anon_3',
		desc: 'All categorical variables will be encrypted using HMAC hashing',
		prec: null,
		precParams: null,
		func: hmacHash,
		params: [["bl_consent", "bl_gender", "bl_ethnicity", "bl_country_res", "bl_comorb___0","bl_comorb___1","bl_comorb___2","bl_comorb___3","bl_comorb___4",
				"bl_comorb___5","bl_comorb___6","bl_comorb___7","bl_comorb___8","bl_comorb___9","bl_comorb___10","bl_comorb___11","bl_comorb___12","bl_comorb___13",
				"bl_comorb___14","bl_comorb___15","bl_comorb___16","bl_comorb___17","bl_comorb___18","bl_comorb___19", "bl_autoimmune_dis_yn","bl_autoimmune_dis___1",
				"bl_autoimmune_dis___2","bl_autoimmune_dis___3","bl_autoimmune_dis___4","bl_autoimmune_dis___5","bl_autoimmune_dis___6","bl_autoimmune_dis___7",
				"bl_autoimmune_dis___8","bl_autoimmune_dis___9","bl_autoimmune_dis___10","bl_autoimmune_dis___11","bl_autoimmune_dis___12","bl_autoimmune_dis___13","bl_allergy_yn","bl_poly_ovary_ynu",
				"bl_oth_prev_malign_yn","bl_prior_immuno_ther_ynu","bl_drug1_interv","bl_drug1_duration","bl_prior_immuno_ther2_ynu","bl_drug2_interv","bl_drug2_duration",
				"bl_prior_immuno_ther3_ynu","bl_drug3_interv","bl_drug3_duration","bl_ecog","bl_edema_side___0","bl_edema_side___1","bl_edema_side___2","bl_edema_side___3",
				"bl_edema_side___4","bl_symp_pres_yn","bl_symp_pres___1","bl_symp_pres___2","bl_symp_pres___3","bl_symp_pres___4","bl_symp_pres___5","bl_symp_pres___6",
				"bl_symp_pres___7","bl_symp_pres___8","bl_symp_pres___9","bl_symp_pres___10","bl_symp_pres___11","bl_tumrel_pain_yn","bl_nrs","bl_pain_site___1",
				"bl_pain_site___2","bl_pain_site___3","bl_pain_site___4","bl_pain_site___5","bl_pain_site___6","bl_pain_site___7","bl_pain_site___8","bl_pain_site___9",
				"bl_ong_antal_ther___1","bl_ong_antal_ther___2","bl_ong_antal_ther___3","bl_ong_antal_ther___4","bl_ong_antal_ther___5","bl_ong_antal_ther___6",
				"bl_ong_antal_ther___7","bl_ong_antal_ther___8","bl_ong_antal_ther___9","bl_ong_antal_ther___10","bl_ong_antal_ther___11","bl_ong_antal_ther___12",
				"bl_menopausal_yn","bl_prev_preg_yn","bl_oral_contra_yn","bl_oral_contra_duration","bl_oral_contra_drug","bl_hormo_replac_yn","bl_hormo_replac_duration",
				"bl_hormo_replac_drug","bl_pathol_diag_site","bl_diag_src_yn","bl_nuclear_pleomorph_yn","bl_necrosis_yn","bl_immuno_stain_camta1","bl_immuno_stain_tfe3",
				"bl_molec_test_wwtr1","bl_molec_test_camta1","bl_molec_test_yap","bl_molec_test_tfe3","bl_pathol_sample","bl_ngs","bl_dis_ext","bl_123_staging___1",
				"bl_123_staging___2","bl_123_staging___3","bl_123_staging___4","bl_123_staging___5","bl_123_staging___6","bl_123_staging___7","bl_123_staging___8",
				"bl_123_imag_thor_yn","bl_123_imag_abdo_yn","bl_123_imag_brain_yn","bl_123_imag_body_yn","bl_123_imag_mri_yn","bl_123_imag_pet_yn","bl_123_imag_bone_yn",
				"bl_123_imag_oth_yn","bl_23_primary_site_chap","bl_123_primary_site","bl_1_primary_site_bone","bl_1_primary_site_bone_spine","bl_1_primary_site_bone_appsk",
				"bl_123_primary_site_limbs","bl_123_primary_site_trunk","bl_123_primary_site_intra","bl_123_primary_site_visce","bl_123_primary_site_visce_oth",
				"bl_123_vis_ves_yn","bl_2_dis_ext_base","bl_3_dis_ext_base___1","bl_3_dis_ext_base___2","bl_3_dis_ext_base___3","bl_3_dis_ext_base___4","bl_3_dis_ext_base___5",
				"bl_3_dis_ext_base___6","bl_3_dis_ext_base___7","bl_23_dis_ext_base_liv_les","bl_23_dis_ext_base_lung_les","bl_23_primary_site_bone","bl_23_primary_site_bone_spine",
				"bl_23_primary_site_bone_appsk","bl_23_dis_ext_base_bone_les","bl_23_dis_ext_base_soft_site___1","bl_23_dis_ext_base_soft_site___2","bl_23_dis_ext_base_soft_site___3",
				"bl_23_dis_ext_base_soft_site___4","bl_23_dis_ext_base_soft_site___5","bl_23_dis_ext_base_soft_les_limb","bl_23_dis_ext_base_soft_les_trunk","bl_23_dis_ext_base_soft_les_abdo",
				"bl_23_dis_ext_base_soft_les_thor","bl_23_dis_ext_base_soft_les_hn","bl_23_dis_ext_base_lymph_site","bl_23_dis_ext_base_oth","bl_3_sero_involv_site___1",
				"bl_3_sero_involv_site___2","bl_3_sero_involv_site___3","bl_3_sero_involv_site___4","bl_3_sero_involv_pleura","bl_3_sero_involv_pleura_shift",
				"bl_3_sero_involv_pleura_nod","bl_3_sero_involv_pleura_eff","bl_3_sero_involv_perito_nod","bl_3_sero_involv_perito_eff","bl_3_sero_involv_perica_nod",
				"bl_3_sero_involv_perica_eff","bl_3_sero_involv_oth_nod","bl_3_sero_involv_oth_eff","bl_123_surv_yn","bl_123_surv_proc___1","bl_123_surv_proc___2",
				"bl_123_surv_proc___3","bl_123_surv_proc___4","bl_123_surv_proc___5","bl_123_surv_proc___6","bl_123_surv_proc___7","bl_123_radio_assess_interv",
				"bl_123_sys_ther_yn","bl_123_sys_ther_set","bl_123_sys_ther_pre_drug","bl_123_sys_ther_pre_disc","bl_123_sys_ther_post_drug","bl_123_sys_ther_post_disc",
				"bl_123_sys_ther_pal_drug","bl_123_sys_ther_br_recist","bl_123_sys_ther_br","bl_123_sys_ther_pal_disc","bl_123_radio_yn","bl_1_radio_set","bl_1_radio_br_recist",
				"bl_1_radio_br","bl_2_radio_site","bl_3_radio_site___1","bl_3_radio_site___2","bl_3_radio_site___3","bl_3_radio_site___4","bl_3_radio_site___5","bl_3_radio_site___6",
				"bl_3_radio_site___7","bl_23_lung_radio_set","bl_23_radio_br_lung_recist","bl_23_radio_br_lung","bl_23_liv_radio_set","bl_23_radio_br_liv_recist","bl_23_radio_br_liver",
				"bl_23_bone_radio_set","bl_23_radio_br_bone_recist","bl_23_radio_br_bone","bl_23_soft_radio_set","bl_23_radio_br_soft_recist","bl_23_radio_br_soft",
				"bl_23_lymph_radio_set","bl_23_radio_br_lymph_recist","bl_23_radio_br_lymph","bl_23_sero_radio_set","bl_23_radio_br_sero_recist","bl_23_radio_br_sero",
				"bl_23_oth_radio_set","bl_23_radio_br_oth_recist","bl_23_radio_br_oth","bl_123_limb_yn","bl_123_limb_set","bl_123_limb_tnf","bl_123_limb_br_recist",
				"bl_123_limb_br","bl_123_abla_yn","bl_2_abla_site","bl_3_abla_site___1","bl_3_abla_site___2","bl_3_abla_site___3","bl_3_abla_site___4","bl_3_abla_site___5",
				"bl_3_abla_site___6","bl_3_abla_site___7","bl_1_abla_set","bl_1_abla_proc","bl_23_abla_set_lung","bl_23_abla_proc_lung","bl_23_abla_set_liv","bl_23_abla_proc_liv",
				"bl_23_abla_set_bone","bl_23_abla_proc_bone","bl_23_abla_set_soft","bl_23_abla_proc_soft","bl_23_abla_set_lymph","bl_23_abla_proc_lymph","bl_23_abla_set_serosal",
				"bl_23_abla_proc_serosal","bl_23_abla_set_oth","bl_23_abla_proc_oth","bl_123_surg_yn","bl_1_surg_tsurg","bl_1_surg_margins","bl_2_surg_site","bl_3_surg_site___1",
				"bl_3_surg_site___2","bl_3_surg_site___3","bl_3_surg_site___4","bl_3_surg_site___5","bl_3_surg_site___6","bl_3_surg_site___7","bl_23_surg_tsurg_lung",
				"bl_23_surg_margins_lung","bl_23_surg_tsurg_liv","bl_23_surg_margins_liv","bl_23_surg_tsurg_bone","bl_23_surg_margins_bone","bl_23_surg_tsurg_soft","bl_23_surg_tsurg_soft_vr",
				"bl_23_surg_margins_soft","bl_23_surg_tsurg_lymph","bl_23_surg_margins_lymph","bl_23_surg_margins_sero","bl_23_surg_tsurg_oth","bl_23_surg_margins_oth","baseline_and_treatment_at_first_presentation_complete",
				"ufu_ecog_ps","ufu_edema___0","ufu_edema___1","ufu_edema___2","ufu_edema___3","ufu_edema___4","ufu_left_lle","ufu_right_lle","ufu_symptoms_yn",
				"ufu_symptoms___1","ufu_symptoms___2","ufu_symptoms___3","ufu_symptoms___4","ufu_symptoms___5","ufu_symptoms___6","ufu_symptoms___7","ufu_symptoms___8","ufu_symptoms___9",
				"ufu_symptoms___10","ufu_symptoms___11","ufu_tum_rel_pain_assess","ufu_tum_rel_pain_assess_nrs","ufu_pain_site___1","ufu_pain_site___2","ufu_pain_site___3","ufu_pain_site___4","ufu_pain_site___5",
				"ufu_pain_site___6","ufu_pain_site___7","ufu_pain_site___8","ufu_pain_site___9","ufu_antal_ther___1","ufu_antal_ther___2","ufu_antal_ther___3","ufu_antal_ther___4","ufu_antal_ther___5",
				"ufu_antal_ther___6","ufu_antal_ther___7","ufu_antal_ther___8","ufu_antal_ther___9","ufu_antal_ther___10","ufu_antal_ther___11","ufu_antal_ther___12","ufu_menopausal_stat","ufu_pregnancies",
				"ufu_oral_contra_yn","ufu_oral_contra_duration","ufu_oral_contra_drug","ufu_oral_contra2_yn","ufu_oral_contra2_duration","ufu_oral_contra2_drug","ufu_oral_contra3_yn","ufu_oral_contra3_duration","ufu_oral_contra3_drug",
				"ufu_hormo_replac_yn","ufu_hormo_replac_duration","ufu_hormo_replac_drug","ufu_hormo_replac2_yn","ufu_hormo_replac2_duration","ufu_hormo_replac2_drug","ufu_hormo_replac3_yn","ufu_hormo_replac3_duration","ufu_hormo_replac3_drug",
				"ufu_surveil_yn","ufu_surveil_proc___1","ufu_surveil_proc___2","ufu_surveil_proc___3","ufu_surveil_proc___4","ufu_surveil_proc___5","ufu_surveil_proc___6","ufu_surveil_proc___7","ufu_surveil_radio_assess_interv",
				"ufu_surveil_br","ufu_surveil_br_recist","ufu_syst_ther_yn","ufu_sys_ther_drug","ufu_sys_ther_assess_interv","ufu_sys_ther_br","ufu_sys_ther_br_recist","ufu_status","unifocal_followup_complete",
				"ulr_multifoc","ulr_staging___1","ulr_staging___2","ulr_staging___3","ulr_staging___4","ulr_staging___5","ulr_staging___6","ulr_staging___7","ulr_staging___8","ulr_ecog_ps","ulr_edema___0",
				"ulr_edema___1","ulr_edema___2","ulr_edema___3","ulr_edema___4","ulr_left_lle","ulr_right_lle","ulr_symptoms_yn","ulr_symptoms___1","ulr_symptoms___2","ulr_symptoms___3","ulr_symptoms___4",
				"ulr_symptoms___5","ulr_symptoms___6","ulr_symptoms___7","ulr_symptoms___8","ulr_symptoms___9","ulr_symptoms___10","ulr_symptoms___11","ulr_tum_rel_pain_assess","ulr_tum_rel_pain_assess_nrs",
				"ulr_pain_site___1","ulr_pain_site___2","ulr_pain_site___3","ulr_pain_site___4","ulr_pain_site___5","ulr_pain_site___6","ulr_pain_site___7","ulr_pain_site___8","ulr_pain_site___9",
				"ulr_antal_ther___1","ulr_antal_ther___2","ulr_antal_ther___3","ulr_antal_ther___4","ulr_antal_ther___5","ulr_antal_ther___6","ulr_antal_ther___7","ulr_antal_ther___8","ulr_antal_ther___9",
				"ulr_antal_ther___10","ulr_antal_ther___11","ulr_antal_ther___12","ulr_menopausal_stat","ulr_pregnancies","ulr_oral_contra_yn","ulr_oral_contra_duration","ulr_oral_contra_drug","ulr_hormo_replac_yn",
				"ulr_hormo_replac_duration","ulr_hormo_replac_drug","ulr_surveil_yn","ulr_surveil_continue_yn","ulr_surveil_proc___1","ulr_surveil_proc___2","ulr_surveil_proc___3","ulr_surveil_proc___4","ulr_surveil_proc___5",
				"ulr_surveil_proc___6","ulr_surveil_proc___7","ulr_surveil_br","ulr_surveil_br_recist","ulr_surveil_radio_assess_interv","ulr_sys_ther_yn","ulr_sys_ther_continue_yn","ulr_sys_ther_schedule_yn","ulr_sys_ther_new_yn",
				"ulr_sys_ther_start_yn","ulr_sys_ther_new_set","ulr_sys_ther_new_pre_drug","ulr_sys_ther_new_post_drug","ulr_sys_ther_new_pal_drug","ulr_sys_ther_br","ulr_sys_ther_br_recist","ulr_radio_yn","ulr_radio_set",
				"ulr_radio_br_recist","ulr_radio_br","ulr_limbperf_yn","ulr_limbperf_set","ulr_limbperf_necro","ulr_limbperf_br_recist","ulr_limbperf_br","ulr_abla_yn","ulr_abla_set","ulr_abla_proc","ulr_surg_yn",
				"ulr_surg_type","ulr_surg_margins","ulr_pathol_yn","ulr_ngs","ulr_pathol_sarref","ulr_pathol_prog","ulr_pathol_prog_pleo","ulr_pathol_prog_necro","ulr_pathol_noprog_diff_mal",
				"ulr_pathol_noprog_diff_mal_spec","ulr_status","unifocal_local_recurrence_complete",
				"udm_staging___1","udm_staging___2","udm_staging___3","udm_staging___4","udm_staging___5","udm_staging___6","udm_staging___7","udm_staging___8","udm_dis_ext___1","udm_dis_ext___2","udm_dis_ext___3",
				"udm_dis_ext___4","udm_dis_ext___5","udm_dis_ext___6","udm_dis_ext___7","udm_dis_ext_liv_les","udm_dis_ext_lung_les","udm_dis_ext_bone_les","udm_dis_ext_soft_site___1","udm_dis_ext_soft_site___2",
				"udm_dis_ext_soft_site___3","udm_dis_ext_soft_site___4","udm_dis_ext_soft_site___5","udm_dis_ext_soft_les_limb","udm_dis_ext_soft_les_trunk","udm_dis_ext_soft_les_abdo","udm_dis_ext_soft_les_thor","udm_dis_ext_soft_les_hn","udm_dis_ext_lymph_site",
				"udm_dis_ext_oth","udm_dis_ext_sero_involv_site___1","udm_dis_ext_sero_involv_site___2","udm_dis_ext_sero_involv_site___3","udm_dis_ext_sero_involv_site___4","udm_dis_ext_sero_involv_pleura","udm_dis_ext_sero_involv_pleura_shift",
				"udm_dis_ext_sero_involv_pleura_nod","udm_dis_ext_sero_involv_pleura_eff","udm_dis_ext_sero_involv_perito_nod","udm_dis_ext_sero_involv_perito_eff","udm_dis_ext_sero_involv_perica_nod","udm_dis_ext_sero_involv_perica_eff",
				"udm_dis_ext_sero_involv_oth_nod","udm_edema","udm_dis_ext_sero_involv_oth_eff","udm_ecog_ps","udm_left_lle","udm_right_lle","udm_symptoms_yn","udm_symptoms___1","udm_symptoms___2","udm_symptoms___3","udm_symptoms___4",
				"udm_symptoms___5","udm_symptoms___6","udm_symptoms___7","udm_symptoms___8","udm_symptoms___9","udm_symptoms___10","udm_symptoms___11","udm_tum_rel_pain_assess","udm_tum_rel_pain_assess_nrs","udm_pain_site___1","udm_pain_site___2",
				"udm_pain_site___3","udm_pain_site___4","udm_pain_site___5","udm_pain_site___6","udm_pain_site___7","udm_pain_site___8","udm_pain_site___9","udm_antal_ther___1","udm_antal_ther___2","udm_antal_ther___3","udm_antal_ther___4",
				"udm_antal_ther___5","udm_antal_ther___6","udm_antal_ther___7","udm_antal_ther___8","udm_antal_ther___9","udm_antal_ther___10","udm_antal_ther___11","udm_antal_ther___12","udm_menopausal_stat","udm_pregnancies","udm_oral_contra_yn",
				"udm_oral_contra_duration","udm_oral_contra_drug","udm_hormo_replac_yn","udm_hormo_replac_duration","udm_hormo_replac_drug","udm_surveil_yn","udm_surveil_continue_yn","udm_surveil_proc___1","udm_surveil_proc___2","udm_surveil_proc___3","udm_surveil_proc___4",
				"udm_surveil_proc___5","udm_surveil_proc___6","udm_surveil_proc___7","udm_surveil_br","udm_surveil_br_recist","udm_surveil_radio_assess_interv","udm_sys_ther_yn","udm_sys_ther_continue_yn","udm_sys_ther_schedule_yn","udm_sys_ther_new_yn","udm_sys_ther_start_yn",
				"udm_sys_ther_new_set","udm_sys_ther_new_pre_drug","udm_sys_ther_new_post_drug","udm_sys_ther_new_pal_drug","udm_sys_ther_br","udm_sys_ther_br_recist","udm_radio_yn","udm_radio_set","udm_radio_site","udm_radio_br","udm_radio_br_recist","udm_limbperf_yn",
				"udm_limbperf_set","udm_limbperf_necro","udm_limbperf_br","udm_limbperf_br_recist","udm_abla_yn","udm_abla_set","udm_abla_site","udm_abla_proc","udm_surg_yn","udm_surg_type","udm_surg_site","udm_surg_margins","udm_bestcare_yn","udm_pathol_yn","udm_ngs",
				"udm_pathol_sarref","udm_pathol_prog","udm_pathol_prog_pleo","udm_pathol_prog_necro","udm_pathol_noprog_diff_mal","udm_pathol_noprog_diff_mal_spec","udm_status","unifocal_distant_metastases_complete",
				"lfu_ecog_ps","lfu_edema___0","lfu_edema___1","lfu_edema___2","lfu_edema___3","lfu_edema___4","lfu_left_lle","lfu_right_lle","lfu_symptoms_yn","lfu_symptoms___1","lfu_symptoms___2","lfu_symptoms___3","lfu_symptoms___4",
				"lfu_symptoms___5","lfu_symptoms___6","lfu_symptoms___7","lfu_symptoms___8","lfu_symptoms___9","lfu_symptoms___10","lfu_symptoms___11","lfu_tum_rel_pain_assess","lfu_tum_rel_pain_assess_nrs","lfu_pain_site___1","lfu_pain_site___2",
				"lfu_pain_site___3","lfu_pain_site___4","lfu_pain_site___5","lfu_pain_site___6","lfu_pain_site___7","lfu_pain_site___8","lfu_pain_site___9","lfu_antal_ther___1","lfu_antal_ther___2","lfu_antal_ther___3","lfu_antal_ther___4",
				"lfu_antal_ther___5","lfu_antal_ther___6","lfu_antal_ther___7","lfu_antal_ther___8","lfu_antal_ther___9","lfu_antal_ther___10","lfu_antal_ther___11","lfu_antal_ther___12","lfu_menopausal_stat","lfu_pregnancies","lfu_oral_contra_yn",
				"lfu_oral_contra_duration","lfu_oral_contra_drug","lfu_oral_contra2_yn","lfu_oral_contra2_duration","lfu_oral_contra2_drug","lfu_oral_contra3_yn","lfu_oral_contra3_duration","lfu_oral_contra3_drug","lfu_hormo_replac_yn","lfu_hormo_replac_duration","lfu_hormo_replac_drug",
				"lfu_hormo_replac2_yn","lfu_hormo_replac2_duration","lfu_hormo_replac2_drug","lfu_hormo_replac3_yn","lfu_hormo_replac3_duration","lfu_hormo_replac3_drug","lfu_surveil_yn","lfu_surveil_proc___1","lfu_surveil_proc___2","lfu_surveil_proc___3","lfu_surveil_proc___4",
				"lfu_surveil_proc___5","lfu_surveil_proc___6","lfu_surveil_proc___7","lfu_surveil_radio_assess_interv","lfu_surveil_br","lfu_surveil_br_recist","lfu_syst_ther_yn","lfu_sys_ther_drug","lfu_sys_ther_assess_interv","lfu_sys_ther_br","lfu_sys_ther_br_recist","lfu_status","locoregional_followup_complete",
				"lpr_staging___1","lpr_staging___2","lpr_staging___3","lpr_staging___4","lpr_staging___5","lpr_staging___6","lpr_staging___7","lpr_staging___8","lpr_ecog_ps","lpr_edema___0","lpr_edema___1","lpr_edema___2","lpr_edema___3","lpr_edema___4","lpr_left_lle","lpr_right_lle","lpr_symptoms_yn",
				"lpr_symptoms___1","lpr_symptoms___2","lpr_symptoms___3","lpr_symptoms___4","lpr_symptoms___5","lpr_symptoms___6","lpr_symptoms___7","lpr_symptoms___8","lpr_symptoms___9","lpr_symptoms___10","lpr_symptoms___11","lpr_tum_rel_pain_assess","lpr_tum_rel_pain_assess_nrs",
				"lpr_pain_site___1","lpr_pain_site___2","lpr_pain_site___3","lpr_pain_site___4","lpr_pain_site___5","lpr_pain_site___6","lpr_pain_site___7","lpr_pain_site___8","lpr_pain_site___9","lpr_antal_ther___1","lpr_antal_ther___2","lpr_antal_ther___3","lpr_antal_ther___4",
				"lpr_antal_ther___5","lpr_antal_ther___6","lpr_antal_ther___7","lpr_antal_ther___8","lpr_antal_ther___9","lpr_antal_ther___10","lpr_antal_ther___11","lpr_antal_ther___12","lpr_menopausal_stat","lpr_pregnancies","lpr_oral_contra_yn","lpr_oral_contra_duration",
				"lpr_oral_contra_drug","lpr_hormo_replac_yn","lpr_hormo_replac_duration","lpr_hormo_replac_drug","lpr_dim_progr","lpr_new_les_same","lpr_new_les_same_num","lpr_new_les_diff","lpr_new_les_diff_num","lpr_new_sero","lpr_new_sero_site___1","lpr_new_sero_site___2",
				"lpr_new_sero_site___3","lpr_new_sero_site___4","lpr_new_sero_pleur_side","lpr_new_sero_pleur_shift","lpr_new_sero_pleur_nod","lpr_new_sero_pleur_effus","lpr_new_sero_perito_nod","lpr_new_sero_perito_effus","lpr_new_sero_perica_nod","lpr_new_sero_perica_effus","lpr_new_sero_oth_nod","lpr_new_sero_oth_effus",
				"lpr_dis_ext___1","lpr_dis_ext___2","lpr_dis_ext___3","lpr_dis_ext___4","lpr_dis_ext___5","lpr_dis_ext___6","lpr_dis_ext___7","lpr_dis_ext_liv_les","lpr_dis_ext_lung_les","lpr_dis_ext_bone_les","lpr_dis_ext_soft_site___1","lpr_dis_ext_soft_site___2","lpr_dis_ext_soft_site___3","lpr_dis_ext_soft_site___4",
				"lpr_dis_ext_soft_site___5","lpr_dis_ext_soft_les_limb","lpr_dis_ext_soft_les_trunk","lpr_dis_ext_soft_les_abdo","lpr_dis_ext_soft_les_thor","lpr_dis_ext_soft_les_hn","lpr_dis_ext_lymph_site",
				"lpr_dis_ext_oth","lpr_dis_ext_sero_involv_site___1","lpr_dis_ext_sero_involv_site___2","lpr_dis_ext_sero_involv_site___3","lpr_dis_ext_sero_involv_site___4","lpr_dis_ext_sero_involv_pleur_side","lpr_dis_ext_sero_involv_pleura_shift",
				"lpr_dis_ext_sero_involv_pleura_nod","lpr_dis_ext_sero_involv_pleura_eff","lpr_dis_ext_sero_involv_perito_nod","lpr_dis_ext_sero_involv_perito_eff","lpr_dis_ext_sero_involv_perica_nod","lpr_dis_ext_sero_involv_perica_eff",
				"lpr_dis_ext_sero_involv_oth_nod","lpr_dis_ext_sero_involv_oth_eff","lpr_surveil_yn","lpr_surveil_continue_yn","lpr_surveil_proc___1","lpr_surveil_proc___2","lpr_surveil_proc___3","lpr_surveil_proc___4","lpr_surveil_proc___5","lpr_surveil_proc___6",
				"lpr_surveil_proc___7","lpr_surveil_br","lpr_surveil_br_recist","lpr_surveil_radio_assess_interv","lpr_sys_ther_yn","lpr_sys_ther_continue_yn","lpr_sys_ther_schedule_yn","lpr_sys_ther_new_yn","lpr_sys_ther_start_yn",
				"lpr_sys_ther_new_set","lpr_sys_ther_new_pre_drug","lpr_sys_ther_new_post_drug","lpr_sys_ther_new_pal_drug","lpr_sys_ther_br","lpr_sys_ther_br_recist","lpr_radio_yn","lpr_radio_site___1","lpr_radio_site___2","lpr_radio_site___3","lpr_radio_site___4","lpr_radio_site___5","lpr_radio_site___6","lpr_radio_site___7",
				"lpr_radio_lung_set","lpr_radio_lung_br_recist","lpr_radio_lung_br","lpr_radio_liver_set","lpr_radio_liver_br_recist","lpr_radio_liver_br","lpr_radio_bone_set","lpr_radio_bone_br_recist","lpr_radio_bone_br","lpr_radio_soft_set","lpr_radio_soft_br_recist","lpr_radio_soft_br","lpr_radio_lymph_set","lpr_radio_lymph_br_recist",
				"lpr_radio_lymph_br","lpr_radio_sero_set","lpr_radio_sero_br_recist","lpr_radio_sero_br","lpr_radio_oth_set","lpr_radio_oth_br_recist","lpr_radio_oth_br","lpr_limbperf_yn","lpr_limbperf_set","lpr_limbperf_necro","lpr_limbperf_br_recist","lpr_limbperf_br","lpr_abla_yn","lpr_abla_site___1","lpr_abla_site___2","lpr_abla_site___3",
				"lpr_abla_site___4","lpr_abla_site___5","lpr_abla_site___6","lpr_abla_site___7","lpr_abla_set_lung","lpr_abla_proc_lung","lpr_abla_set_liver","lpr_abla_proc_liver","lpr_abla_set_bone","lpr_abla_proc_bone","lpr_abla_set_soft","lpr_abla_proc_soft","lpr_abla_set_lymph","lpr_abla_proc_lymph","lpr_abla_set_serosal",
				"lpr_abla_proc_serosal","lpr_abla_set_oth","lpr_abla_proc_oth","lpr_surg_yn","lpr_surg_site___1","lpr_surg_site___2","lpr_surg_site___3","lpr_surg_site___4","lpr_surg_site___5","lpr_surg_site___6","lpr_surg_site___7","lpr_surg_type_lung","lpr_surg_margins_lung","lpr_surg_type_liver","lpr_surg_margins_liver",
				"lpr_surg_type_bone","lpr_surg_margins_bone","lpr_surg_type_soft","lpr_surg_margins_soft","lpr_surg_type_lymph","lpr_surg_margins_lymph","lpr_surg_margins_serosal","lpr_surg_type_oth","lpr_surg_margins_oth","lpr_bestcare_yn","lpr_pathol_yn","lpr_ngs","lpr_pathol_sarref","lpr_pathol_prog","lpr_pathol_prog_pleo",
				"lpr_pathol_prog_necro","lpr_pathol_noprog_diff_mal","lpr_pathol_noprog_diff_mal_spec","lpr_status","locoregional_progression_complete",
				"sfu_ecog_ps","sfu_edema___0","sfu_edema___1","sfu_edema___2","sfu_edema___3","sfu_edema___4","sfu_left_lle","sfu_right_lle","sfu_symptoms_yn","sfu_symptoms___1","sfu_symptoms___2","sfu_symptoms___3","sfu_symptoms___4",
				"sfu_symptoms___5","sfu_symptoms___6","sfu_symptoms___7","sfu_symptoms___8","sfu_symptoms___9","sfu_symptoms___10","sfu_symptoms___11","sfu_tum_rel_pain_assess","sfu_tum_rel_pain_assess_nrs","sfu_pain_site___1","sfu_pain_site___2",
				"sfu_pain_site___3","sfu_pain_site___4","sfu_pain_site___5","sfu_pain_site___6","sfu_pain_site___7","sfu_pain_site___8","sfu_pain_site___9","sfu_antal_ther___1","sfu_antal_ther___2","sfu_antal_ther___3","sfu_antal_ther___4",
				"sfu_antal_ther___5","sfu_antal_ther___6","sfu_antal_ther___7","sfu_antal_ther___8","sfu_antal_ther___9","sfu_antal_ther___10","sfu_antal_ther___11","sfu_antal_ther___12","sfu_menopausal_stat","sfu_pregnancies","sfu_oral_contra_yn",
				"sfu_oral_contra_duration","sfu_oral_contra_drug","sfu_oral_contra2_yn","sfu_oral_contra2_duration","sfu_oral_contra2_drug","sfu_oral_contra3_yn","sfu_oral_contra3_duration","sfu_oral_contra3_drug","sfu_hormo_replac_yn","sfu_hormo_replac_duration","sfu_hormo_replac_drug",
				"sfu_hormo_replac2_yn","sfu_hormo_replac2_duration","sfu_hormo_replac2_drug","sfu_hormo_replac3_yn","sfu_hormo_replac3_duration","sfu_hormo_replac3_drug","sfu_surveil_yn","sfu_surveil_proc___1","sfu_surveil_proc___2","sfu_surveil_proc___3","sfu_surveil_proc___4",
				"sfu_surveil_proc___5","sfu_surveil_proc___6","sfu_surveil_proc___7","sfu_surveil_radio_assess_interv","sfu_surveil_br","sfu_surveil_br_recist","sfu_syst_ther_yn","sfu_sys_ther_drug","sfu_sys_ther_assess_interv","sfu_sys_ther_br","sfu_sys_ther_br_recist","sfu_status","systemic_metastases_followup_complete",
				"spr_staging___1","spr_staging___2","spr_staging___3","spr_staging___4","spr_staging___5","spr_staging___6","spr_staging___7","spr_staging___8","spr_ecog_ps","spr_edema___0","spr_edema___1","spr_edema___2","spr_edema___3","spr_edema___4","spr_left_lle","spr_right_lle","spr_symptoms_yn",
				"spr_symptoms___1","spr_symptoms___2","spr_symptoms___3","spr_symptoms___4","spr_symptoms___5","spr_symptoms___6","spr_symptoms___7","spr_symptoms___8","spr_symptoms___9",
				"spr_symptoms___10","spr_symptoms___11","spr_tum_rel_pain_assess","spr_tum_rel_pain_assess_nrs","spr_pain_site___1","spr_pain_site___2","spr_pain_site___3","spr_pain_site___4","spr_pain_site___5",
				"spr_pain_site___6","spr_pain_site___7","spr_pain_site___8","spr_pain_site___9","spr_antal_ther___1","spr_antal_ther___2","spr_antal_ther___3","spr_antal_ther___4","spr_antal_ther___5",
				"spr_antal_ther___6","spr_antal_ther___7","spr_antal_ther___8","spr_antal_ther___9","spr_antal_ther___10","spr_antal_ther___11","spr_antal_ther___12","spr_menopausal_stat","spr_pregnancies",
				"spr_oral_contra_yn","spr_oral_contra_duration","spr_oral_contra_drug","spr_hormo_replac_yn","spr_hormo_replac_duration","spr_hormo_replac_drug","spr_dim_progr","spr_new_les_same","spr_new_les_diff","spr_new_sero","spr_new_sero_site___1","spr_new_sero_site___2",
				"spr_new_sero_site___3","spr_new_sero_site___4","spr_new_sero_pleur_side","spr_new_sero_pleur_shift","spr_new_sero_pleur_nod","spr_new_sero_pleur_effus","spr_new_sero_perito_nod","spr_new_sero_perito_effus","spr_new_sero_perica_nod","spr_new_sero_perica_effus",
				"spr_new_sero_oth_nod","spr_new_sero_oth_effus","spr_new_sero_worse","spr_new_sero_worse_site___1","spr_new_sero_worse_site___2","spr_new_sero_worse_site___3","spr_new_sero_worse_site___4","spr_new_sero_worse_pleur_side","spr_new_sero_worse_pleur_shift","spr_new_sero_worse_pleur_nod",
				"spr_new_sero_worse_pleur_eff","spr_new_sero_worse_perito_nod","spr_new_sero_worse_perito_eff","spr_new_sero_worse_perica_nod","spr_new_sero_worse_perica_eff","spr_new_sero_worse_oth_nod","spr_new_sero_worse_oth_eff","spr_dis_ext___1","spr_dis_ext___2","spr_dis_ext___3",
				"spr_dis_ext___4","spr_dis_ext___5","spr_dis_ext___6","spr_dis_ext___7","spr_dis_ext_liv_les","spr_dis_ext_lung_les","spr_dis_ext_bone_les","spr_dis_ext_soft_site___1","spr_dis_ext_soft_site___2","spr_dis_ext_soft_site___3","spr_dis_ext_soft_site___4","spr_dis_ext_soft_site___5",
				"spr_dis_ext_soft_les_limb","spr_dis_ext_soft_les_trunk","spr_dis_ext_soft_les_abdo","spr_dis_ext_soft_les_thor","spr_dis_ext_soft_les_hn","spr_dis_ext_lymph_site","spr_dis_ext_oth","spr_dis_ext_sero_involv_site___1","spr_dis_ext_sero_involv_site___2","spr_dis_ext_sero_involv_site___3",
				"spr_dis_ext_sero_involv_site___4","spr_dis_ext_sero_involv_pleur_side","spr_dis_ext_sero_involv_pleur_shift","spr_dis_ext_sero_involv_pleur_nod","spr_dis_ext_sero_involv_pleur_eff","spr_dis_ext_sero_involv_perito_nod","spr_dis_ext_sero_involv_perito_eff","spr_dis_ext_sero_involv_perica_nod",
				"spr_dis_ext_sero_involv_perica_eff","spr_dis_ext_sero_involv_oth_nod","spr_dis_ext_sero_involv_oth_eff","spr_surveil_yn","spr_surveil_continue_yn","spr_surveil_proc___1","spr_surveil_proc___2","spr_surveil_proc___3","spr_surveil_proc___4","spr_surveil_proc___5","spr_surveil_proc___6",
				"spr_surveil_proc___7","spr_surveil_br","spr_surveil_br_recist","spr_surveil_radio_assess_interv","spr_sys_ther_yn","spr_sys_ther_continue_yn","spr_sys_ther_schedule_yn","spr_sys_ther_new_yn","spr_sys_ther_start_yn","spr_sys_ther_new_set","spr_sys_ther_new_pre_drug","spr_sys_ther_new_post_drug",
				"spr_sys_ther_new_pal_drug","spr_sys_ther_br","spr_sys_ther_br_recist","spr_radio_yn","spr_radio_site___1","spr_radio_site___2","spr_radio_site___3","spr_radio_site___4","spr_radio_site___5","spr_radio_site___6","spr_radio_site___7","spr_radio_lung_set","spr_radio_lung_br_recist","spr_radio_lung_br",
				"spr_radio_liver_set","spr_radio_liver_br_recist","spr_radio_liver_br","spr_radio_bone_set","spr_radio_bone_br_recist","spr_radio_bone_br","spr_radio_soft_set","spr_radio_soft_br_recist","spr_radio_soft_br","spr_radio_lymph_set","spr_radio_lymph_br_recist","spr_radio_lymph_br","spr_radio_sero_set",
				"spr_radio_sero_br_recist","spr_radio_sero_br","spr_radio_oth_set","spr_radio_oth_br_recist","spr_radio_oth_br","spr_limbperf_yn","spr_limbperf_set","spr_limbperf_necro","spr_limbperf_br_recist","spr_limbperf_br","spr_abla_yn","spr_abla_site___1","spr_abla_site___2","spr_abla_site___3","spr_abla_site___4",
				"spr_abla_site___5","spr_abla_site___6","spr_abla_site___7","spr_abla_set_lung","spr_abla_proc_lung","spr_abla_set_liver","spr_abla_proc_liver","spr_abla_set_bone","spr_abla_proc_bone","spr_abla_set_soft","spr_abla_proc_soft","spr_abla_set_lymph","spr_abla_proc_lymph","spr_abla_set_serosal","spr_abla_proc_serosal",
				"spr_abla_set_oth","spr_abla_proc_oth","spr_surg_yn","spr_surg_site___1","spr_surg_site___2","spr_surg_site___3","spr_surg_site___4","spr_surg_site___5","spr_surg_site___6","spr_surg_site___7","spr_surg_type_lung","spr_surg_margins_lung","spr_surg_type_liver","spr_surg_margins_liver","spr_surg_type_bone",
				"spr_surg_margins_bone","spr_surg_margins_soft","spr_surg_type_lymph","spr_surg_margins_lymph","spr_surg_margins_serosal","spr_surg_type_oth","spr_surg_margins_oth","spr_bestcare_yn","spr_pathol_yn","spr_ngs","spr_pathol_sarref","spr_pathol_prog","spr_pathol_prog_pleo","spr_pathol_prog_necro","spr_pathol_noprog_diff_mal",
				"spr_pathol_noprog_diff_mal_spec","spr_status","systemic_metastases_progression_complete",
				"lsu_status","lsu_clinical_trials_yn","life_status_update_complete"
]]
	}
];
